### ISSUE TITLE
Error installing dependenciesfrom requirements.txt

### ISSUE THREAD

**Issue by Andrej730** [boltsparts/boltsparts#1]
Error installing dependencies from requirements.txt

```
ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from versions: none)
ERROR: No matching distribution found for pkg-resources==0.0.0
```

Trying to install it without specifying version lead me to the error too:
```
> pip install pkg-resources
ERROR: Could not find a version that satisfies the requirement pkg-resources (from versions: none)
ERROR: No matching distribution found for pkg-resources
```

It seems like a known issue - https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command

Should we just remove it from requirements.txt?

**Comment by berndhahnebach** [comment]
I don't mind would you go for a PR and reference this issue in the commit message?
